param(
    [switch]$check
)
$ErrorActionPreference = "Stop"

$skillsRoot = "skills"
$catalogMdPath = "docs/CATALOG.md"
$catalogJsonPath = "docs/CATALOG.json"

# Ensure docs directory exists
$docsDir = Split-Path -Parent "$catalogMdPath"
if (-not (Test-Path -LiteralPath "$docsDir")) {
    New-Item -ItemType Directory -Path "$docsDir" -Force | Out-Null
}

# Collect skills
$skills = @()
if (Test-Path -LiteralPath "$skillsRoot") {
    $files = Get-ChildItem -LiteralPath "$skillsRoot" -Recurse -Filter "SKILL.md" -File -ErrorAction SilentlyContinue
    foreach ($file in $files) {
        $full = "$($file.FullName)"
        try {
            $raw = Get-Content -LiteralPath "$full" -Raw -ErrorAction Stop
        } catch {
            continue
        }
        # Extract frontmatter name
        $name = $null
        $desc = ""
        if ($raw -match '(?s)^\s*---\s*\r?\n(.*?)\r?\n---\s*\r?\n') {
            $fm = $Matches[1]
            if ($fm -match '(?m)^\s*name\s*:\s*["'']?(.+?)["'']?\s*$') {
                $name = $Matches[1].Trim().Trim('"').Trim("'").Trim()
            }
            if ($fm -match '(?m)^\s*description\s*:\s*"(.*)"\s*$') {
                $desc = $Matches[1].Trim()
            } elseif ($fm -match "(?m)^\s*description\s*:\s*'(.*)'\s*$") {
                $desc = $Matches[1].Trim()
            } elseif ($fm -match '(?m)^\s*description\s*:\s*(.+)\s*$') {
                $desc = $Matches[1].Trim().Trim('"').Trim("'").Trim()
            }
        }
        if (-not $name) {
            $name = $file.Directory.Name
        }
        # Compute relative path with forward slashes for catalog display
        $rel = $full.Replace((Get-Location).Path + [System.IO.Path]::DirectorySeparatorChar, "").Replace('\', '/')
        # Normalize to skills/... path
        if ($rel -notmatch '^skills/') {
            # Fallback: try to get relative via Resolve-Path relative
            try {
                $rel2 = Resolve-Path -LiteralPath "$full" -Relative -ErrorAction SilentlyContinue
                if ($rel2) { $rel = "$rel2".Replace('\', '/').TrimStart('./') }
            } catch {}
        }
        # Determine group prefix (first folder under skills)
        $parts = $rel -split '/'
        $group = ""
        if ($parts.Count -ge 2) { $group = $parts[1] }

        $skills += [PSCustomObject]@{
            Name        = "$name"
            Description = "$desc"
            Path        = "$rel"
            Group       = "$group"
        }
    }
}

# Sort by Group then Name
$skills = $skills | Sort-Object -Property Group, Name

# Build CATALOG.md
$md = @"
# Catalog

> Auto-generated by scripts/generate-catalog.ps1 -- do not edit manually. Run pwsh ./scripts/generate-catalog.ps1 after adding/modifying skills.

| Skill | Description | Path |
|---|---|---|
"@

if ($skills -and @($skills).Count -gt 0) {
    # Optionally group by prefix with subheadings
    $currentGroup = $null
    foreach ($s in $skills) {
        if ($s.Group -ne $currentGroup) {
            $currentGroup = $s.Group
            $md += "`n`n### $currentGroup`n`n| Skill | Description | Path |`n|---|---|---|`n"
        }
        $safeDesc = $s.Description.Replace('|', '\|').Replace("`r", " ").Replace("`n", " ")
        $md += "| $($s.Name) | $safeDesc | $($s.Path) |`n"
    }
} else {
    # No skills yet -- keep table header and add placeholder row note
    $md += "`n"
}

# Also ensure at top-level table header exists even when grouped; the initial header satisfies spec check for "| Skill |"
# If grouped, we already have tables per group. Ensure file always contains "| Skill |"
if ($md -notmatch '\| Skill \|') {
    $md = "# Catalog`n`n| Skill | Description | Path |`n|---|---|---|`n"
}

$generatedMd = $md.TrimEnd() + "`n"

# Handle --check mode
if ($check) {
    if (-not (Test-Path -LiteralPath "$catalogMdPath")) {
        Write-Error "CATALOG.md missing -- run generate-catalog.ps1 to create it"
        exit 1
    }
    $existing = Get-Content -LiteralPath "$catalogMdPath" -Raw -ErrorAction Stop
    # Normalize line endings and trailing whitespace for comparison (handles Set-Content extra newline)
    $normExisting = $existing.Replace("`r`n", "`n").TrimEnd() + "`n"
    $normGenerated = $generatedMd.Replace("`r`n", "`n").TrimEnd() + "`n"
    if ($normExisting -ne $normGenerated) {
        Write-Error "CATALOG.md is stale -- run pwsh ./scripts/generate-catalog.ps1 to regenerate"
        # Show diff hint
        Write-Host "Expected CATALOG.md content differs from current file."
        exit 1
    }
    Write-Host "generate-catalog: CATALOG.md is up to date (check passed)"
    # Also check CATALOG.json exists
    if (-not (Test-Path -LiteralPath "$catalogJsonPath")) {
        Write-Error "CATALOG.json missing"
        exit 1
    }
    Write-Host "generate-catalog: CATALOG.json exists"
    exit 0
}

# Write CATALOG.md (use LiteralPath, UTF8)
Set-Content -LiteralPath "$catalogMdPath" -Value $generatedMd -Encoding UTF8

# Build CATALOG.json -- ensure array output even for single skill (PS5 quirk)
$jsonArray = @()
foreach ($s in $skills) {
    $jsonArray += [PSCustomObject]@{
        name        = $s.Name
        description = $s.Description
        path        = $s.Path
        group       = $s.Group
    }
}
if (@($jsonArray).Count -eq 0) {
    $jsonText = "[]"
} elseif (@($jsonArray).Count -eq 1) {
    $single = $jsonArray[0] | ConvertTo-Json -Depth 4
    $jsonText = "[$single]"
} else {
    $jsonText = $jsonArray | ConvertTo-Json -Depth 4
}
Set-Content -LiteralPath "$catalogJsonPath" -Value $jsonText -Encoding UTF8

$skillCount = @($skills).Count
Write-Host "generate-catalog: wrote $catalogMdPath ($skillCount skills) and $catalogJsonPath"
exit 0
